### ISSUE TITLE
License missing?

### ISSUE THREAD

**Issue by trittich** [ArnoldSouza/SapRefresh#1]
Dear Arnold,

I found your project and think it might be a fit to be used for my master thesis. However, since my work might be used in a commercial context, I need to be sure that I am allowed to use your tool. You did not add any information regarding your intended license, yet. Can you maybe specify the license by adding a license file which fits your needs? Github also got a feature where you can just choose a proper license.
Find more information here: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository 

If you are unsure about this topic and just want people to be able to use your work as easily as possible, the MIT license is one of the more generous licenses and might be appropriate which would then also make it possible for me to use your software. But I do not want to push you in any direction here, its your decision for sure.

Best regards,
Tim

**Comment by ArnoldSouza** [comment]
Hello Tim, the license was added using the MIT layout. Have fun with your master thesis =)
